name: Aia Azure Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      workflow_python_version: 3.9
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/Checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.workflow_python_version }}
          cache: poetry

      - name: Install Python Dependencies
        run: |
          poetry install
          
      - name: Install Azure Cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Before Pulumi Preview
        run: |
          ls -al
          python3 -m venv venv/ 
          source venv/bin/activate
          ls -al
          pip install pulumi pulumi-azure-native pulumi-random
      
      # - name: Azure Login with scripts
      #   run: |
      #     ./pulumi_login.sh -p datasci
      #     ./pulumi_wrapper.sh stack select ax-dev
      #     ./pulumi_wrapper.sh preview
      
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ax-dev
          cloud-url: azblob://datasci
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_KEYVAULT_AUTH_VIA_CLI: true
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
