name: Aia Azure Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      workflow_python_version: 3.9
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/Checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.workflow_python_version }}
          cache: poetry

      - name: Install poetry
        run: |
          pipx install poetry
          
      - name: Install Azure Cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version
      
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Install Python Dependencies
        run: |
          poetry install

      # Test, build, publish
      - name: Test Azure commands
        run: |
          az version
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Azure CLI script file
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az version
      
      - name: Pulumi Login
        run: |
          ./pulumi_login.sh -p datasci
          ./pulumi_wrapper.sh stack select ax-dev
          # ls -al
          # cat .pulumi-dev.env
          # python3 -m venv venv/ 
          # source venv/bin/activate
          # ls -al
          # pip install pulumi pulumi-azure-native pulumi-random
          # ./pulumi_wrapper.sh preview
      
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
