name: Aia Azure Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      workflow_python_version: 3.9
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/Checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          # Install Azure cli
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.workflow_python_version }}
          cache: poetry
      - name: Install Python Dependencies
        # env:
          # POETRY_HTTP_BASIC_ARTIFACTORY_DEPS_USERNAME: ${{ secrets.MERATIVE_POETRY_HTTP_BASIC_PYPI_USERNAME }}
          # POETRY_HTTP_BASIC_ARTIFACTORY_DEPS_PASSWORD: ${{ secrets.MERATIVE_POETRY_HTTP_BASIC_PYPI_PASSWORD }}
        run: |
          poetry install

      # Test, build, publish

      - name: Install az cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.38.0
          inlineScript: |
            az version
            echo "Hello world!"