name: Aia Azure Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      workflow_python_version: 3.9
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/Checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry
          
      - name: Install az cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version
          echo "Hello world!"
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.workflow_python_version }}
          cache: poetry

      - name: Install Python Dependencies
        # env:
          # POETRY_HTTP_BASIC_ARTIFACTORY_DEPS_USERNAME: ${{ secrets.MERATIVE_POETRY_HTTP_BASIC_PYPI_USERNAME }}
          # POETRY_HTTP_BASIC_ARTIFACTORY_DEPS_PASSWORD: ${{ secrets.MERATIVE_POETRY_HTTP_BASIC_PYPI_PASSWORD }}
        run: |
          poetry install

      # Test, build, publish
      - name: Test Azure commands
        run: |
          az version
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Azure CLI script file
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.39.0
      #     inlineScript: |
      #       az version
      #       echo "Hello world!"
      
      - name: Pulumi Login
        run: |
          ./pulumi_login.sh -p datasci
          ./authorize_keyvault_for_self.sh
      
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
